-- FastAPI-owned identity tables. Idempotent for existing Neon and fresh installs.
CREATE TABLE IF NOT EXISTS public.accounts_user (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password varchar(128) NOT NULL, last_login timestamptz,
  is_superuser boolean NOT NULL DEFAULT false,
  public_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
  email varchar(254) NOT NULL UNIQUE, full_name varchar(200) NOT NULL,
  phone_e164 varchar(16) NOT NULL DEFAULT '', role varchar(32) NOT NULL DEFAULT 'field_agent',
  district_ids integer[] NOT NULL DEFAULT '{}', is_active boolean NOT NULL DEFAULT true,
  is_staff boolean NOT NULL DEFAULT false, mfa_enforced boolean NOT NULL DEFAULT false,
  date_joined timestamptz NOT NULL DEFAULT now(), deactivated_at timestamptz
);
CREATE INDEX IF NOT EXISTS accounts_user_role_idx ON public.accounts_user(role);

CREATE TABLE IF NOT EXISTS public.otp_totp_totpdevice (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(64) NOT NULL DEFAULT 'default', confirmed boolean NOT NULL DEFAULT true,
  key varchar(80) NOT NULL, step integer NOT NULL DEFAULT 30, t0 bigint NOT NULL DEFAULT 0,
  digits integer NOT NULL DEFAULT 6, tolerance integer NOT NULL DEFAULT 1,
  drift integer NOT NULL DEFAULT 0, last_t bigint NOT NULL DEFAULT -1,
  throttling_failure_count integer NOT NULL DEFAULT 0,
  throttling_failure_timestamp timestamptz, created_at timestamptz, last_used_at timestamptz,
  user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS otp_totp_user_idx ON public.otp_totp_totpdevice(user_id);

CREATE TABLE IF NOT EXISTS public.token_blacklist_outstandingtoken (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token text NOT NULL,
  created_at timestamptz, expires_at timestamptz NOT NULL,
  user_id bigint REFERENCES public.accounts_user(id) ON DELETE SET NULL,
  jti varchar(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS public.token_blacklist_blacklistedtoken (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blacklisted_at timestamptz NOT NULL DEFAULT now(),
  token_id bigint NOT NULL UNIQUE REFERENCES public.token_blacklist_outstandingtoken(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.axes_accessattempt (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agent varchar(255) NOT NULL DEFAULT '', ip_address inet, username varchar(255),
  http_accept varchar(1025) NOT NULL DEFAULT '',
  path_info varchar(255) NOT NULL DEFAULT '/api/v1/auth/login/',
  attempt_time timestamptz NOT NULL DEFAULT now(), get_data text NOT NULL DEFAULT '',
  post_data text NOT NULL DEFAULT '', failures_since_start integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS axes_attempt_username_idx ON public.axes_accessattempt(username, attempt_time);
