/**
 * Billing queries and mutations.
 *
 * Money is never formatted here. The server sends a `display` block with every
 * figure already grouped the Indian way (6,45,519.00, not 645,519.00) because
 * the grouping rule lives in one place — `apps/billing/money.py` — and a
 * second implementation in TypeScript is a second implementation to get wrong.
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from './client'

export type InvoiceStatus =
  | 'draft'
  | 'issued'
  | 'on_hold'
  | 'part_paid'
  | 'paid'
  | 'cancelled'
  | 'discarded'

export interface BillingEntity {
  id: string
  code: string
  legal_name: string
  address_lines: string[]
  state_code: string
  state_name: string | null
  gstin: string | null
  bank_name: string | null
  bank_account_no: string | null
  template_code: string
  valid_from: string
  valid_to: string | null
}

export interface InvoiceLine {
  id?: string
  line_no: number
  description: string
  hsn_sac: string | null
  quantity: string
  unit: string
  /** Generated by the database. Read-only, and null for non-area units. */
  quantity_ha: string | null
  rate: string
  rate_is_tax_inclusive: boolean
  line_taxable_value: string
  line_tax_amount: string
  line_total: string
  location_note: string | null
}

export interface InvoiceRow {
  id: string
  invoice_no: string | null
  entity_code: string
  invoice_date: string
  financial_year: string | null
  buyer_name: string
  organisation_name: string | null
  taxable_value: string
  tax_amount: string
  total_value: string
  amount_outstanding: string
  status: InvoiceStatus
  tax_treatment: string
  display: { total: string; outstanding: string }
}

export interface Invoice extends InvoiceRow {
  // 🔴 The detail endpoint returns the issuing company as a *code*, not as a
  // nested object. This interface is hand-written rather than generated, and
  // it previously claimed `entity: BillingEntity`; the page read
  // `invoice.entity.legal_name`, which was `undefined.legal_name` on every
  // invoice and blanked the screen. Resolve the name from
  // `useBillingEntities()` instead.
  entity_code: string
  buyer_address: string | null
  buyer_gstin: string | null
  buyer_state_name: string | null
  buyer_is_govt_uin: boolean
  buyer_order_no: string | null
  work_order_ref: string | null
  letter_ref: string | null
  data_link_url: string | null
  consignee_name: string | null
  consignee_address: string | null
  template_code: string
  tax_rate_pct: string
  amount_in_words: string | null
  amount_received: string
  total_area_ha: string | null
  cancellation_reason: string | null
  notes: string | null
  lines: InvoiceLine[]
  payments: Payment[]
  display: { total: string; outstanding: string; taxable: string; tax: string; received: string }
}

export interface Payment {
  id: string
  received_on: string
  amount: string
  /** Server-formatted with Indian digit grouping. Render this, not `amount`. */
  amount_display: string
  mode: string | null
  reference: string | null
  note: string | null
}

/** A line as typed into the form — before the server has computed anything. */
export interface DraftLine {
  line_no: number
  description: string
  hsn_sac: string
  quantity: string
  unit: string
  rate: string
  rate_is_tax_inclusive: boolean
  location_note: string
}

export interface DraftInvoice {
  entity_code: string
  template_code: string
  invoice_date: string
  buyer_name: string
  buyer_address: string
  buyer_gstin: string
  buyer_pan: string
  buyer_is_govt_uin: boolean
  consignee_name: string
  consignee_address: string
  buyer_order_no: string
  work_order_ref: string
  letter_ref: string
  data_link_url: string
  tax_treatment: string
  tax_rate_pct: string
  notes: string
  lines: DraftLine[]
}

export interface PreviewResult {
  html: string
  taxable_value: string
  tax_amount: string
  total_value: string
  amount_in_words: string
  total_area_ha: string
  /** What this invoice *would* be numbered. Reading this allocates nothing. */
  next_invoice_no: string
  pdf_backend: string | null
  display: { taxable: string; tax: string; total: string }
}

export interface ExtractionResult {
  entity_code: string
  invoice_date: string | null
  buyer_name: string | null
  buyer_address: string | null
  buyer_gstin: string | null
  buyer_pan: string | null
  buyer_state_code: string | null
  consignee_name: string | null
  consignee_address: string | null
  buyer_order_no: string | null
  work_order_ref: string | null
  letter_ref: string | null
  data_link_url: string | null
  tax_rate_pct: number
  lines: Array<Partial<DraftLine> & { description: string }>
  extraction_id: string
  _warnings: string[]
  _confidence: Record<string, number>
  _needs_review: boolean
  _notes: string | null
}

export interface RegisterSummary {
  count: number
  taxable_value: string
  tax_amount: string
  total_value: string
  amount_received: string
  amount_outstanding: string
  total_area_ha: string
  display: {
    taxable: string
    tax: string
    total: string
    received: string
    outstanding: string
  }
}

// ---------------------------------------------------------------------------

export function useBillingEntities() {
  return useQuery({
    queryKey: ['billing-entities'],
    queryFn: () => api<BillingEntity[]>('/api/v1/billing-entities/?current=true'),
    // The two companies change roughly never; refetching them on every screen
    // is noise on a village connection.
    staleTime: 60 * 60 * 1000,
  })
}

export function useInvoices(filters: Record<string, string> = {}) {
  const query = new URLSearchParams(
    Object.entries(filters).filter(([, v]) => v !== '' && v != null),
  ).toString()

  return useQuery({
    queryKey: ['invoices', filters],
    queryFn: () => api<{ results: InvoiceRow[]; next: string | null }>(
      `/api/v1/invoices/${query ? `?${query}` : ''}`,
    ),
  })
}

export function useInvoiceSummary(filters: Record<string, string> = {}) {
  const query = new URLSearchParams(
    Object.entries(filters).filter(([, v]) => v !== '' && v != null),
  ).toString()

  return useQuery({
    queryKey: ['invoice-summary', filters],
    queryFn: () => api<RegisterSummary>(`/api/v1/invoices/summary/${query ? `?${query}` : ''}`),
  })
}

export function useInvoice(id: string | undefined) {
  return useQuery({
    queryKey: ['invoice', id],
    queryFn: () => api<Invoice>(`/api/v1/invoices/${id}/`),
    enabled: Boolean(id),
  })
}

/**
 * Render the document from form data, without saving anything.
 *
 * This is what makes the create screen live rather than a save-and-check
 * loop — it runs the same template and the same arithmetic the issued PDF
 * will use, so what you see is the document, not an approximation of it.
 */
export function usePreview() {
  return useMutation({
    mutationFn: (draft: DraftInvoice) =>
      api<PreviewResult>('/api/v1/invoices/preview/', { method: 'POST', body: draft }),
  })
}

export function useCreateInvoice() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (payload: unknown) =>
      api<Invoice>('/api/v1/invoices/', { method: 'POST', body: payload }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['invoices'] }),
  })
}

/**
 * Issue an invoice.
 *
 * 🔴 `invoice_sha256` is the check run being relied on. If the draft changed
 * after those checks were shown, the server answers 409 rather than issuing
 * something the person did not review. `acknowledge` carries the non-blocking
 * warnings they accepted, with their reasons — both are stored.
 */
export function useIssueInvoice() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({
      id,
      ...body
    }: {
      id: string
      invoice_sha256?: string
      acknowledge?: Array<{ code: string; reason: string }>
    }) =>
      api<{ invoice_no: string; status: InvoiceStatus; warnings: unknown[] }>(
        `/api/v1/invoices/${id}/issue/`,
        { method: 'POST', body },
      ),
    onSuccess: (_, { id }) => {
      qc.invalidateQueries({ queryKey: ['invoice', id] })
      qc.invalidateQueries({ queryKey: ['invoices'] })
    },
  })
}

export function useCancelInvoice() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ id, reason }: { id: string; reason: string }) =>
      api(`/api/v1/invoices/${id}/cancel/`, { method: 'POST', body: { reason } }),
    onSuccess: (_, { id }) => {
      qc.invalidateQueries({ queryKey: ['invoice', id] })
      qc.invalidateQueries({ queryKey: ['invoices'] })
    },
  })
}

export function useRecordPayment() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ id, ...body }: { id: string; received_on: string; amount: string; mode?: string; reference?: string }) =>
      api(`/api/v1/invoices/${id}/payments/`, { method: 'POST', body }),
    onSuccess: (_, { id }) => {
      qc.invalidateQueries({ queryKey: ['invoice', id] })
      qc.invalidateQueries({ queryKey: ['invoices'] })
    },
  })
}

/**
 * Upload a document and get the form back filled in.
 *
 * 🔴 Returns a draft, never an invoice. Nothing is saved and no number is
 * allocated — what comes back is a suggestion with a confidence attached, and
 * `_warnings` is the list a human has to look at before issuing.
 */
export function useExtractInvoice() {
  return useMutation({
    mutationFn: ({ file, entityCode }: { file: File; entityCode: string }) => {
      const form = new FormData()
      form.append('file', file)
      form.append('entity_code', entityCode)
      return api<ExtractionResult>('/api/v1/invoices/extract/', { method: 'POST', body: form })
    },
  })
}
