/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Returns a token pair plus the user's role, territory and MFA state.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Blacklist the refresh token. Access tokens expire on their own in 15m.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Current user, role, permissions and territory.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enrol/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin MFA enrolment
         * @description Create an unconfirmed TOTP device and return its provisioning URI.
         */
        post: operations["auth_mfa_enrol_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify MFA code
         * @description Verify a TOTP code and re-issue a token pair with mfa_satisfied=true.
         *
         *     The re-issue matters: without it the client keeps a token whose claim says
         *     MFA is outstanding, and every protected call keeps failing.
         */
        post: operations["auth_mfa_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Change password and revoke every outstanding session (Doc 12 §13).
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Unauthenticated liveness probe for the ALB.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        /**
         * @description Issues the token pair and reports whether MFA still has to be satisfied.
         *
         *     🔴 Doc 12 §1: MFA is mandatory for data_ops, campaign_manager, compliance
         *     and admin. The token is issued either way, but `mfa_satisfied: false` means
         *     the client must complete /auth/mfa/verify/ before the token is accepted by
         *     any protected endpoint — enforced by IsMFAVerified, not by client goodwill.
         */
        Login: {
            email: string;
            password: string;
        };
        LogoutRequest: {
            refresh: string;
        };
        MFAEnrolResponse: {
            /** @description otpauth:// URI. Render as a QR code; never log it. */
            provisioning_uri: string;
        };
        MFAVerify: {
            token: string;
        };
        PasswordChange: {
            current_password: string;
            new_password: string;
        };
        /**
         * @description * `field_agent` - Field / BD Agent
         *     * `bd_manager` - BD Manager
         *     * `project_manager` - Project Manager
         *     * `campaign_manager` - Campaign Manager
         *     * `data_ops` - Data Ops Analyst
         *     * `leadership` - Leadership
         *     * `compliance` - Compliance Officer
         *     * `admin` - System Admin
         * @enum {string}
         */
        RoleEnum: "field_agent" | "bd_manager" | "project_manager" | "campaign_manager" | "data_ops" | "leadership" | "compliance" | "admin";
        TokenPair: {
            access: string;
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description `GET /auth/me/` — identity, role, permissions and territory. */
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            /**
             * @description Primary role. Drives RLS scoping and the MFA requirement.
             *
             *     * `field_agent` - Field / BD Agent
             *     * `bd_manager` - BD Manager
             *     * `project_manager` - Project Manager
             *     * `campaign_manager` - Campaign Manager
             *     * `data_ops` - Data Ops Analyst
             *     * `leadership` - Leadership
             *     * `compliance` - Compliance Officer
             *     * `admin` - System Admin
             */
            readonly role: components["schemas"]["RoleEnum"];
            /** @description LGD district codes this user may access. */
            readonly district_ids: number[];
            readonly is_cross_territory: boolean;
            /** @description Set automatically for roles in MFA_REQUIRED_ROLES. */
            readonly mfa_enforced: boolean;
            readonly permissions: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Refresh token blacklisted */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_mfa_enrol_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MFAEnrolResponse"];
                };
            };
        };
    };
    auth_mfa_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MFAVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["MFAVerify"];
                "multipart/form-data": components["schemas"]["MFAVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Invalid or expired code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Changed; all sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
