# Generated by Django 5.2.17 on 2026-08-26 06:35

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_code",
                    models.TextField(
                        blank=True,
                        help_text="Human-friendly: FPO-UP-000123",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fpo", "FPO (Farmer Producer Organisation)"),
                            ("acs", "Cooperative society / PACS"),
                            ("sugar_mill", "Sugar mill"),
                            ("cooperative_federation", "Cooperative federation"),
                            ("input_dealer", "Input dealer"),
                            (
                                "ngo_promoting_institution",
                                "NGO / promoting institution",
                            ),
                            ("government_body", "Government body"),
                            ("private_company", "Private company"),
                            ("bank_nbfc", "Bank / NBFC"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("defunct", "Defunct"),
                            ("merged", "Merged"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="prospect",
                        max_length=16,
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        choices=[
                            ("producer_company", "Producer company"),
                            ("cooperative_society", "Cooperative society"),
                            ("section_8_company", "Section 8 company"),
                            ("private_limited", "Private limited"),
                            ("public_limited", "Public limited"),
                            ("llp", "LLP"),
                            ("partnership", "Partnership"),
                            ("proprietorship", "Proprietorship"),
                            ("trust", "Trust"),
                            ("society", "Society"),
                            ("statutory_body", "Statutory body"),
                            ("unregistered", "Unregistered"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "name_local",
                    models.TextField(
                        blank=True, help_text="Devanagari, kept verbatim.", null=True
                    ),
                ),
                ("short_name", models.TextField(blank=True, null=True)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Every other spelling this org is known by. Matching reads these.",
                        size=None,
                    ),
                ),
                (
                    "cin",
                    models.CharField(
                        blank=True, max_length=21, null=True, verbose_name="CIN"
                    ),
                ),
                ("registration_no", models.TextField(blank=True, null=True)),
                ("registration_act", models.TextField(blank=True, null=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "pan_masked",
                    models.CharField(
                        blank=True,
                        help_text="Masked only: ABCDE****F. A full PAN never enters this column.",
                        max_length=14,
                        null=True,
                        verbose_name="PAN (masked)",
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="GSTIN"
                    ),
                ),
                ("udyam_no", models.TextField(blank=True, null=True)),
                ("address_line1", models.TextField(blank=True, null=True)),
                ("address_line2", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("website", models.TextField(blank=True, null=True)),
                ("established_year", models.SmallIntegerField(blank=True, null=True)),
                ("member_count", models.IntegerField(blank=True, null=True)),
                ("women_member_count", models.IntegerField(blank=True, null=True)),
                (
                    "annual_turnover_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "turnover_fy",
                    models.CharField(
                        blank=True, help_text="e.g. 2024-25", max_length=7, null=True
                    ),
                ),
                (
                    "promoting_agency",
                    models.TextField(
                        blank=True,
                        help_text="NABARD, SFAC, NCDC, state department",
                        null=True,
                    ),
                ),
                (
                    "scheme_reference",
                    models.TextField(
                        blank=True,
                        help_text="e.g. 10,000 FPO scheme cluster id",
                        null=True,
                    ),
                ),
                (
                    "quality_tier",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("quarantine", "Quarantine"),
                        ],
                        default="bronze",
                        max_length=16,
                    ),
                ),
                ("completeness_score", models.SmallIntegerField(default=0)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'core"."organisation',
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrgAnnualMetric",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "fy",
                    models.CharField(
                        help_text="e.g. 2024-25", max_length=7, verbose_name="FY"
                    ),
                ),
                (
                    "metric_code",
                    models.TextField(
                        help_text="cane_crushed_lmt, sugar_produced_lmt, turnover_inr, ..."
                    ),
                ),
                (
                    "metric_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("unit", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "organisation annual metric",
                "db_table": 'core"."org_annual_metric',
                "ordering": ["-fy", "metric_code"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CooperativeProfile",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        db_column="organisation_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="cooperative_profile",
                        serialize=False,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "society_type",
                    models.TextField(
                        blank=True,
                        help_text="PACS, cane society, dairy, marketing, credit, multipurpose",
                        null=True,
                    ),
                ),
                ("registration_act", models.TextField(blank=True, null=True)),
                ("is_pacs", models.BooleanField(default=False, verbose_name="Is PACS")),
                (
                    "is_computerised",
                    models.BooleanField(
                        blank=True, help_text="PACS computerisation scheme", null=True
                    ),
                ),
                (
                    "deposit_base_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "loan_outstanding_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("area_of_operation", models.TextField(blank=True, null=True)),
                ("villages_covered", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "cooperative profile",
                "db_table": 'core"."cooperative_profile',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FpoProfile",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        db_column="organisation_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="fpo_profile",
                        serialize=False,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "authorised_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "paid_up_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "share_value_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("shareholder_count", models.IntegerField(blank=True, null=True)),
                (
                    "business_lines",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="input sale, output aggregation, custom hiring, processing",
                        size=None,
                    ),
                ),
                (
                    "licences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="seed, fertiliser, pesticide, FSSAI, mandi",
                        size=None,
                    ),
                ),
                ("has_storage", models.BooleanField(blank=True, null=True)),
                (
                    "storage_capacity_mt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("has_processing_unit", models.BooleanField(blank=True, null=True)),
                ("processing_details", models.TextField(blank=True, null=True)),
                ("custom_hiring_centre", models.BooleanField(blank=True, null=True)),
                (
                    "equity_grant_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("credit_guarantee", models.BooleanField(blank=True, null=True)),
                (
                    "cbbo_name",
                    models.TextField(
                        blank=True,
                        help_text="Cluster Based Business Organisation",
                        null=True,
                        verbose_name="CBBO",
                    ),
                ),
                (
                    "implementing_agency",
                    models.TextField(
                        blank=True, help_text="SFAC / NABARD / NCDC / NAFED", null=True
                    ),
                ),
                (
                    "last_agm_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last AGM date"
                    ),
                ),
                (
                    "last_annual_return_fy",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "primary_crops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="ref.crop ids",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO profile",
                "db_table": 'core"."fpo_profile',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SugarMillProfile",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        db_column="organisation_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="sugar_mill_profile",
                        serialize=False,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("cooperative", "Cooperative"),
                            ("public_sector", "Public sector"),
                            ("joint_sector", "Joint sector"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "crushing_capacity_tcd",
                    models.IntegerField(
                        blank=True,
                        help_text="Tonnes of cane per day.",
                        null=True,
                        verbose_name="Crushing capacity (TCD)",
                    ),
                ),
                ("installed_year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "cogeneration_mw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Cogeneration (MW)",
                    ),
                ),
                (
                    "distillery_capacity_klpd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distillery capacity (KLPD)",
                    ),
                ),
                ("has_ethanol_plant", models.BooleanField(default=False)),
                (
                    "has_cbg_plant",
                    models.BooleanField(default=False, verbose_name="Has CBG plant"),
                ),
                (
                    "refinery_capacity_tpd",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Refinery capacity (TPD)"
                    ),
                ),
                ("cane_command_villages", models.IntegerField(blank=True, null=True)),
                ("registered_cane_growers", models.IntegerField(blank=True, null=True)),
                (
                    "avg_recovery_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Avg recovery %",
                    ),
                ),
                (
                    "cane_price_srp_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cane price (SAP)",
                    ),
                ),
                ("season_start_month", models.SmallIntegerField(blank=True, null=True)),
                ("season_end_month", models.SmallIntegerField(blank=True, null=True)),
                ("is_operational", models.BooleanField(default=True)),
                (
                    "federation_membership",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="ISMA, NFCSF, state sugarfed",
                        size=None,
                    ),
                ),
                (
                    "cane_payment_status",
                    models.TextField(
                        blank=True, help_text="'current' or 'arrears'", null=True
                    ),
                ),
                (
                    "cane_arrears_inr_cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cane arrears (INR cr)",
                    ),
                ),
            ],
            options={
                "verbose_name": "sugar mill profile",
                "db_table": 'core"."sugar_mill_profile',
                "managed": False,
            },
        ),
    ]
