# Generated by Django 5.2.17 on 2026-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lgd_code", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.TextField()),
                ("name_local", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "block / tehsil",
                "db_table": 'ref"."block',
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("name_local", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.TextField(
                        blank=True,
                        help_text="cereal, pulse, oilseed, cash, horticulture, fodder",
                        null=True,
                    ),
                ),
                (
                    "default_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                            ("perennial", "Perennial"),
                            ("annual", "Annual"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": 'ref"."crop',
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CropVariety",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("maturity_days", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "crop varieties",
                "db_table": 'ref"."crop_variety',
                "ordering": ["crop__name", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lgd_code", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.TextField()),
                ("name_local", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": 'ref"."district',
                "ordering": ["state__name", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("lgd_code", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.TextField(unique=True)),
                ("name_local", models.TextField(blank=True, null=True)),
                ("iso_code", models.TextField(blank=True, null=True)),
                (
                    "is_ut",
                    models.BooleanField(default=False, verbose_name="Union Territory"),
                ),
            ],
            options={
                "verbose_name": "state / UT",
                "verbose_name_plural": "states / UTs",
                "db_table": 'ref"."state',
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lgd_code", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.TextField()),
                ("name_local", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": 'ref"."village',
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
