# Generated by Django 5.2.17 on 2026-08-25 06:30

import apps.accounts.models
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("phone_e164", models.CharField(blank=True, max_length=16)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("field_agent", "Field / BD Agent"),
                            ("bd_manager", "BD Manager"),
                            ("project_manager", "Project Manager"),
                            ("campaign_manager", "Campaign Manager"),
                            ("data_ops", "Data Ops Analyst"),
                            ("leadership", "Leadership"),
                            ("compliance", "Compliance Officer"),
                            ("admin", "System Admin"),
                        ],
                        default="field_agent",
                        help_text="Primary role. Drives RLS scoping and the MFA requirement.",
                        max_length=32,
                    ),
                ),
                (
                    "district_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="LGD district codes this user may access.",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "mfa_enforced",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically for roles in MFA_REQUIRED_ROLES.",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
                "indexes": [
                    models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx")
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
