# Generated by Django 5.2.17 on 2026-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contradiction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entity_type", models.TextField()),
                ("entity_id", models.UUIDField()),
                ("field_name", models.TextField()),
                ("value_a", models.TextField(blank=True, null=True)),
                ("value_b", models.TextField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": 'dq"."contradiction',
                "ordering": ["-detected_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FieldProvenance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entity_type", models.TextField()),
                ("entity_id", models.UUIDField()),
                ("field_name", models.TextField()),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "source_reference",
                    models.TextField(
                        blank=True,
                        help_text="URL, file name, row number, MoU id.",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                ("collected_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by", models.UUIDField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "field provenance",
                "db_table": 'dq"."field_provenance',
                "ordering": ["-collected_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.TextField(
                        help_text="Stable identifier used by collector code.",
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("public_registry", "Public registry"),
                            ("open_government_data", "Open government data"),
                            ("official_website", "Official website"),
                            ("industry_directory", "Industry directory"),
                            ("partner_agreement", "Partner agreement"),
                            ("field_collection", "Field collection"),
                            ("inbound_signup", "Inbound signup"),
                            ("theta_analytics", "Theta Analytics legacy"),
                            ("purchased_licensed", "Purchased / licensed"),
                            ("manual_entry", "Manual entry"),
                            ("inferred", "Inferred"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "legal_basis",
                    models.TextField(
                        help_text="🔴 Mandatory. Why we may hold data from this source. A source with no written legal basis must not be approved."
                    ),
                ),
                ("licence", models.TextField(blank=True, null=True)),
                ("contains_pii", models.BooleanField(default=False)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="🔴 R1. Collectors refuse to run against an unapproved source.",
                    ),
                ),
                (
                    "approved_by",
                    models.TextField(
                        blank=True, help_text="A named human, not a system.", null=True
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_cadence", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'dq"."source',
                "ordering": ["code"],
                "managed": False,
            },
        ),
    ]
