"""Invoice register shapes (INVOICE.md)."""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from pydantic import BaseModel, field_validator


class MoneyDisplay(BaseModel):
    """Pre-formatted figures. See `backend/money.py` for why the server does this.

    🔴 Indian digit grouping is done here and never in TypeScript. The detail
    screen reads `taxable` and `tax` as well as `total` and `outstanding`; they
    were absent, so it rendered "₹undefined" for two of the four figures on
    every invoice.
    """

    total: str
    outstanding: str
    taxable: str
    tax: str
    received: str


class InvoiceRow(BaseModel):
    id: uuid.UUID
    invoice_no: str | None
    entity_code: str
    invoice_date: date
    financial_year: str | None
    buyer_name: str
    status: str
    tax_treatment: str
    taxable_value: Decimal
    tax_amount: Decimal
    total_value: Decimal
    amount_outstanding: Decimal
    display: MoneyDisplay


class InvoiceLineOut(BaseModel):
    line_no: int
    description: str
    hsn_sac: str | None
    quantity: Decimal
    unit: str
    #: Generated by the database. Null for non-area units.
    quantity_ha: Decimal | None
    rate: Decimal
    line_taxable_value: Decimal
    line_tax_amount: Decimal
    line_total: Decimal


class InvoicePaymentOut(BaseModel):
    amount: Decimal
    amount_display: str
    received_on: date
    mode: str | None
    reference: str | None


class InvoiceDetail(InvoiceRow):
    buyer_address: str | None
    buyer_gstin: str | None
    buyer_order_no: str | None
    work_order_ref: str | None
    letter_ref: str | None
    payment_terms: str | None
    tax_rate_pct: Decimal
    amount_in_words: str | None
    amount_received: Decimal
    issued_at: datetime | None
    cancelled_at: datetime | None
    cancellation_reason: str | None
    lines: list[InvoiceLineOut]
    payments: list[InvoicePaymentOut]


class InvoicePage(BaseModel):
    count: int
    results: list[InvoiceRow]


class SummaryDisplay(BaseModel):
    taxable: str
    tax: str
    total: str
    received: str
    outstanding: str


class RegisterSummary(BaseModel):
    count: int
    taxable_value: Decimal
    tax_amount: Decimal
    total_value: Decimal
    amount_received: Decimal
    amount_outstanding: Decimal
    total_area_ha: Decimal
    display: SummaryDisplay


# ---------------------------------------------------------------------------
# Writes
# ---------------------------------------------------------------------------


class InvoiceLineIn(BaseModel):
    """
    A line as the client sends it.

    🔴 No amounts. `line_taxable_value`, `line_tax_amount` and `line_total` are
    computed server-side in `api/money.py` — a client that could post its own
    totals could post an invoice whose lines do not sum to its header.
    """

    line_no: int | None = None
    description: str
    hsn_sac: str | None = None
    quantity: Decimal
    unit: str
    rate: Decimal
    rate_is_tax_inclusive: bool = False
    tax_rate_pct: Decimal | None = None
    location_note: str | None = None


class InvoiceCreate(BaseModel):
    billing_entity: uuid.UUID
    invoice_date: date
    due_date: date | None = None
    buyer_name: str
    buyer_address: str | None = None
    buyer_gstin: str | None = None
    buyer_state_code: str | None = None
    buyer_is_govt_uin: bool = False
    buyer_order_no: str | None = None
    work_order_ref: str | None = None
    letter_ref: str | None = None
    payment_terms: str | None = None
    organisation: uuid.UUID | None = None
    tax_treatment: str = "igst"
    tax_rate_pct: Decimal = Decimal("18.00")
    place_of_supply_state_code: str | None = None
    lines: list[InvoiceLineIn] = []


class InvoiceUpdate(BaseModel):
    """Draft edits. Every field optional; `lines` replaces the set when given."""

    invoice_date: date | None = None
    due_date: date | None = None
    buyer_name: str | None = None
    buyer_address: str | None = None
    buyer_gstin: str | None = None
    buyer_state_code: str | None = None
    buyer_order_no: str | None = None
    work_order_ref: str | None = None
    letter_ref: str | None = None
    payment_terms: str | None = None
    tax_treatment: str | None = None
    tax_rate_pct: Decimal | None = None
    lines: list[InvoiceLineIn] | None = None


class IssueResponse(BaseModel):
    invoice_no: str
    status: str
    #: Non-blocking findings from the checks that ran at issue. Returned so the
    #: UI can show what was accepted rather than silently dropping it — the
    #: full run is stored as `crm.invoice_check_run` issue evidence.
    warnings: list[dict] = []


class CancelRequest(BaseModel):
    reason: str


class PaymentRequest(BaseModel):
    amount: Decimal
    received_on: date
    mode: str | None = None
    reference: str | None = None
    note: str | None = None


class BillingEntityOut(BaseModel):
    id: uuid.UUID
    code: str
    legal_name: str
    state_code: str | None
    gstin: str | None
    bank_name: str | None
    bank_account_no: str | None
    bank_ifsc: str | None
    template_code: str
    valid_from: date
    valid_to: date | None

    model_config = {"from_attributes": True}


class PreviewLineIn(BaseModel):
    """
    A line as the *preview* receives it — deliberately lenient.

    🔴 Separate from `InvoiceLineIn` on purpose. The live preview fires on
    every keystroke, so a quantity typed before a rate must render the document
    as far as it goes: an unfilled field is not an invalid one, and answering
    400 makes the preview look like a broken renderer.

    Creating an invoice keeps the strict shape. Nothing rendered here is
    saved, no number is allocated, and `compute_line` reads a missing figure as
    zero — so the leniency buys a working preview and gives up nothing.
    """

    line_no: int | None = None
    description: str = ""
    hsn_sac: str | None = None
    quantity: Decimal | None = None
    unit: str = "each"
    rate: Decimal | None = None
    rate_is_tax_inclusive: bool = False
    tax_rate_pct: Decimal | None = None
    location_note: str | None = None

    @field_validator("quantity", "rate", "tax_rate_pct", mode="before")
    @classmethod
    def _blank_is_absent(cls, value: object) -> object:
        """
        🔴 An empty string is an unfilled box, not an invalid number.

        A controlled React input holds `""` before anyone types, so the live
        preview posts `quantity: ""` on the first keystroke. Pydantic reads
        that as "not a decimal" and answers 400 — which is correct for a
        create and wrong for a preview, where the document should simply
        render as far as it goes.
        """
        if isinstance(value, str) and not value.strip():
            return None
        return value


class PreviewRequest(BaseModel):
    """
    An invoice that does not exist yet, rendered as the document it would be.

    🔴 The entity may be named either way, and that is not laziness.

    The create screen holds `entity_code` ("TEPL") because that is what the
    dropdown binds to; the register holds the row's UUID. Requiring only the
    UUID meant the live preview posted `entity_code` and got a 400 on every
    keystroke — a broken preview that looked like a flaky renderer. Accepting
    both is one `or` here versus a reshape of the form's state.
    """

    billing_entity: uuid.UUID | None = None
    entity_code: str | None = None
    invoice_date: date
    buyer_name: str = ""
    buyer_address: str | None = None
    buyer_gstin: str | None = None
    buyer_state_code: str | None = None
    tax_treatment: str = "igst"
    tax_rate_pct: Decimal = Decimal("18.00")
    lines: list[PreviewLineIn] = []
