"""
Payment request providers — manual UPI, a deterministic fake gateway, and the
seam a real one plugs into.

🔴 **A payment request is not a payment.** Nothing in this module creates a
`crm.invoice_payment` row. A UPI URI is a convenience for the person paying and
carries no information about whether they paid; INVOICE.md §11.2 is explicit
that claiming otherwise is forbidden, and the status vocabulary reflects it —
`awaiting_manual_confirmation` is where a UPI request stays until a human
records a receipt or a signed webhook matches it.

🔴 **Signature verification happens over raw request bytes.** Re-serialising a
parsed body changes whitespace and key order, so a signature computed over the
re-serialised form verifies something the sender never signed. The webhook
route therefore reads `await request.body()` and passes those exact bytes here.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any, Protocol

logger = logging.getLogger("backend.payments")


class PaymentProviderError(RuntimeError):
    """A provider failed. 🔴 Never converted into a successful response."""


@dataclass(frozen=True)
class PaymentRequestResult:
    provider: str
    provider_reference: str | None
    payload_url: str | None
    qr_svg: str | None
    status: str
    expires_at: datetime | None


@dataclass(frozen=True)
class WebhookEvent:
    """A verified (or rejected) event, parsed but not yet acted on."""

    provider_event_id: str
    event_type: str | None
    signature_verified: bool
    provider_timestamp: datetime | None
    amount: Decimal | None
    currency: str | None
    reference: str | None
    raw: dict[str, Any]
    failure: str | None = None


class PaymentProvider(Protocol):
    name: str

    async def create_request(
        self,
        *,
        invoice_no: str,
        amount: Decimal,
        currency: str,
        payee_name: str,
        note: str,
        idempotency_key: str,
    ) -> PaymentRequestResult: ...

    def parse_webhook(self, body: bytes, headers: dict[str, str]) -> WebhookEvent: ...


# ---------------------------------------------------------------------------
# Manual UPI
# ---------------------------------------------------------------------------


def _upi_uri(*, vpa: str, payee: str, amount: Decimal, note: str, ref: str) -> str:
    """
    A UPI deep link, per the NPCI parameter set.

    `am` is fixed and `cu` is INR. The transaction note carries the invoice
    number so the receipt a customer sends back can be matched to a document
    by a person reading it.
    """
    from urllib.parse import quote

    params = {
        "pa": vpa,
        "pn": payee,
        "am": f"{amount:.2f}",
        "cu": "INR",
        "tn": note[:50],
        "tr": ref[:35],
    }
    query = "&".join(f"{key}={quote(str(value), safe='')}" for key, value in params.items())
    return f"upi://pay?{query}"


def _qr_svg(payload: str, *, size: int = 240) -> str:
    """
    A QR code as inline SVG, with no dependency.

    🔴 Rendered rather than fetched. A QR generated by an image API would send
    a payment URI containing the company's VPA and an invoice amount to a third
    party on every page view, and the artifact people photograph should not
    depend on somebody else's uptime.
    """
    modules = _qr_modules(payload)
    count = len(modules)
    scale = max(1, size // (count + 8))
    quiet = 4 * scale
    dimension = count * scale + 2 * quiet

    rects = []
    for y, row in enumerate(modules):
        run_start = None
        for x in range(count + 1):
            dark = x < count and row[x]
            if dark and run_start is None:
                run_start = x
            elif not dark and run_start is not None:
                rects.append(
                    f'<rect x="{quiet + run_start * scale}" y="{quiet + y * scale}" '
                    f'width="{(x - run_start) * scale}" height="{scale}"/>'
                )
                run_start = None

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{dimension}" '
        f'height="{dimension}" viewBox="0 0 {dimension} {dimension}" '
        f'role="img" aria-label="UPI payment QR code">'
        f'<rect width="{dimension}" height="{dimension}" fill="#ffffff"/>'
        f'<g fill="#000000">{"".join(rects)}</g></svg>'
    )


def _qr_modules(payload: str) -> list[list[bool]]:
    """
    Encode `payload` as a QR matrix.

    Uses `segno` when it is installed and raises a clear error otherwise. The
    alternative — hand-rolling Reed-Solomon here — is several hundred lines
    whose bugs would produce a QR code that scans to the wrong amount, which is
    the worst failure available in this file.
    """
    try:
        import segno
    except ImportError as error:
        raise PaymentProviderError(
            "QR rendering needs `segno` (pip install segno). The UPI link "
            "itself works without it — the request is created with a payload "
            "URL and no QR image."
        ) from error

    qr = segno.make(payload, error="m")
    return [[bool(cell) for cell in row] for row in qr.matrix]


class ManualUpiProvider:
    """
    A UPI link and QR the customer pays with, out of band.

    🔴 The resulting request is `awaiting_manual_confirmation` and stays there.
    Generating it, showing it, or watching somebody scan it records nothing —
    only a human-entered receipt creates a payment.
    """

    name = "manual_upi"

    def __init__(self, vpa: str, payee_name: str) -> None:
        if not vpa:
            raise PaymentProviderError(
                "Manual UPI is not configured: set UPI_VPA (and UPI_PAYEE_NAME) "
                "in the environment. A link to an empty VPA would be a link to "
                "nowhere printed on an invoice."
            )
        self.vpa = vpa
        self.payee_name = payee_name or "Theta"

    async def create_request(
        self,
        *,
        invoice_no: str,
        amount: Decimal,
        currency: str,
        payee_name: str,
        note: str,
        idempotency_key: str,
    ) -> PaymentRequestResult:
        if currency != "INR":
            raise PaymentProviderError("UPI settles in INR only.")

        reference = invoice_no.replace("/", "-")
        uri = _upi_uri(
            vpa=self.vpa,
            payee=payee_name or self.payee_name,
            amount=amount,
            note=note or f"Invoice {invoice_no}",
            ref=reference,
        )
        try:
            qr = _qr_svg(uri)
        except PaymentProviderError as error:
            logger.warning("UPI QR not rendered: %s", error)
            qr = None

        return PaymentRequestResult(
            provider=self.name,
            provider_reference=reference,
            payload_url=uri,
            qr_svg=qr,
            # 🔴 The whole point of this status.
            status="awaiting_manual_confirmation",
            expires_at=None,
        )

    def parse_webhook(self, body: bytes, headers: dict[str, str]) -> WebhookEvent:
        raise PaymentProviderError(
            "Manual UPI has no webhook. A UPI payment is confirmed by a person "
            "entering the receipt."
        )


# ---------------------------------------------------------------------------
# The deterministic fake gateway
# ---------------------------------------------------------------------------


class FakeGatewayProvider:
    """
    A gateway that behaves like a real one, offline.

    Signs with HMAC-SHA256 over the raw body plus a timestamp, exactly the
    shape Razorpay, Stripe and Cashfree all use. That similarity is the point:
    the reconciliation logic, the replay window and the idempotency behaviour
    are exercised for real, so enabling a live provider is a class swap rather
    than a rewrite of everything downstream.
    """

    name = "fake_gateway"

    def __init__(self, secret: str) -> None:
        self.secret = secret or "fake-gateway-secret"

    async def create_request(
        self,
        *,
        invoice_no: str,
        amount: Decimal,
        currency: str,
        payee_name: str,
        note: str,
        idempotency_key: str,
    ) -> PaymentRequestResult:
        # Derived from the idempotency key, so replaying a request produces the
        # same reference rather than a second one at the provider.
        reference = "fake_" + hashlib.sha256(idempotency_key.encode()).hexdigest()[:20]
        return PaymentRequestResult(
            provider=self.name,
            provider_reference=reference,
            payload_url=f"https://fake-gateway.invalid/pay/{reference}",
            qr_svg=None,
            status="pending_provider",
            expires_at=datetime.now(UTC) + timedelta(days=7),
        )

    def sign(self, body: bytes, timestamp: str) -> str:
        """Used by tests to build a valid event, and by nothing in production."""
        return hmac.new(
            self.secret.encode(), timestamp.encode() + b"." + body, hashlib.sha256
        ).hexdigest()

    def parse_webhook(self, body: bytes, headers: dict[str, str]) -> WebhookEvent:
        lower = {key.lower(): value for key, value in headers.items()}
        signature = lower.get("x-webhook-signature", "")
        timestamp = lower.get("x-webhook-timestamp", "")

        try:
            payload = json.loads(body)
        except json.JSONDecodeError:
            return WebhookEvent(
                provider_event_id=f"unparseable-{uuid.uuid4().hex}",
                event_type=None,
                signature_verified=False,
                provider_timestamp=None,
                amount=None,
                currency=None,
                reference=None,
                raw={},
                failure="body is not JSON",
            )

        expected = self.sign(body, timestamp)
        verified = bool(signature) and hmac.compare_digest(expected, signature)

        sent_at = None
        if timestamp.isdigit():
            sent_at = datetime.fromtimestamp(int(timestamp), tz=UTC)

        amount = payload.get("amount")
        return WebhookEvent(
            # 🔴 An event with no id gets a synthetic one so the row can still
            # be stored. Storing it is what makes the rejection reviewable.
            provider_event_id=str(payload.get("event_id") or f"missing-{uuid.uuid4().hex}"),
            event_type=payload.get("event"),
            signature_verified=verified,
            provider_timestamp=sent_at,
            amount=Decimal(str(amount)) if amount is not None else None,
            currency=payload.get("currency"),
            reference=payload.get("reference"),
            raw=payload,
            failure=None if verified else "signature mismatch",
        )


# ---------------------------------------------------------------------------
# Selection
# ---------------------------------------------------------------------------


def get_provider(name: str) -> PaymentProvider:
    """
    🔴 An unknown name raises. There is no default provider — a payment route
    that silently fell back to a fake would look like it was taking money.
    """
    from backend.config import settings

    key = (name or "").lower()
    if key == "manual_upi":
        return ManualUpiProvider(settings.upi_vpa, settings.upi_payee_name)
    if key in ("fake_gateway", "fake"):
        return FakeGatewayProvider(settings.payment_webhook_secret)
    raise PaymentProviderError(
        f"'{name}' is not a payment provider this build knows. "
        f"Available: manual_upi, fake_gateway. A live gateway is enabled by "
        f"adding its class here and supplying credentials — see DEPLOYMENT.md."
    )
